spring:
  application:
    name: admin-user-registration-login

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace

server:
  port: 8084

